apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  initContainers:
  - name: sidecar-app
    image: busybox:latest
    command:
      - sleep
      - infinity
  containers:
  - name: main-app
    image: nginx:latest