apiVersion: v1
kind: ServiceAccount
metadata:
  name: repro-sa
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-delete
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "-1"
