apiVersion: v1
kind: ServiceAccount
metadata:
  name: repro-sa
  annotations:
    # 关键点：这里定义了多个 Hook，且包含 pre-delete
    # 在 Bug 修复前，Argo CD 无法正确解析这种逗号分隔的写法，导致 PreDelete 时并未从 hook-succeeded 策略中得知需要重建
    helm.sh/hook: pre-install,pre-upgrade,pre-delete
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "-1"
